# Generated by Django 3.1.1 on 2020-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, default='default_restaurent.png', upload_to=''),
        ),
    ]
