# Generated by Django 3.1.1 on 2020-11-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0003_auto_20201113_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='nomail@gamil.com', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_options',
            field=models.CharField(default='CASH', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seating',
            field=models.CharField(default='INDOOR', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='services',
            field=models.CharField(default='BREAKFAST LUNCH DINNER CAFE NIGHTLIGHT', max_length=100),
        ),
    ]
