# Generated by Django 3.1.1 on 2020-11-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0004_auto_20201113_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='payment_options',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='seating',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='food_items.Item'),
        ),
    ]
