# Generated by Django 3.1.1 on 2020-11-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0006_auto_20201116_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
