# Generated by Django 3.1.1 on 2020-11-17 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0007_auto_20201117_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='created',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opened',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
