# Generated by Django 3.1.1 on 2020-11-19 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0010_auto_20201119_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='food_items.restaurant'),
        ),
    ]
