# Generated by Django 3.1.1 on 2020-11-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0011_auto_20201119_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='item',
            name='restaurant',
            field=models.ManyToManyField(null=True, related_name='restaurant', to='food_items.Restaurant'),
        ),
    ]
