# Generated by Django 3.1.3 on 2020-11-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201110_2105'),
        ('food_items', '0013_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPerQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=4, max_digits=50000)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('itemperquantity', models.ManyToManyField(related_name='itemperquantity', to='food_items.ItemPerQuantity')),
            ],
        ),
    ]
