# Generated by Django 3.1.3 on 2020-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0015_auto_20201125_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='itemperquantity',
            field=models.ManyToManyField(blank=True, null=True, related_name='itemperquantity', to='food_items.ItemPerQuantity'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(),
        ),
    ]
