# Generated by Django 3.1.3 on 2020-11-25 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0017_auto_20201125_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='itemperquantity',
        ),
        migrations.AddField(
            model_name='itemperquantity',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_items.cart'),
        ),
    ]
