# Generated by Django 3.1.3 on 2020-11-25 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0018_auto_20201125_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemperquantity',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='itemperquantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemperquantity', to='food_items.itemperquantity'),
        ),
    ]
