# Generated by Django 3.1.3 on 2020-11-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0022_auto_20201126_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='diet',
            field=models.CharField(default='veg', max_length=10),
        ),
    ]
