# Generated by Django 3.1.3 on 2020-11-26 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0023_item_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemperquantity',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_items.item'),
        ),
    ]
