# Generated by Django 3.1.3 on 2020-11-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0025_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='typeofaddress',
            field=models.CharField(default='HOME', max_length=10),
        ),
    ]
