# Generated by Django 3.1.3 on 2020-11-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201110_2105'),
        ('food_items', '0026_delivery_typeofaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(null=True, related_name='items', to='food_items.Item')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest', to='food_items.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryaddress', models.CharField(max_length=150)),
                ('total', models.FloatField()),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('deliverytime', models.DateTimeField(blank=True)),
                ('status', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust', to='home.customer')),
            ],
        ),
    ]
