# Generated by Django 3.1.3 on 2020-11-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201110_2105'),
        ('food_items', '0030_auto_20201127_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
        migrations.RemoveField(
            model_name='pending',
            name='items',
        ),
        migrations.AddField(
            model_name='pending',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_items.itemperquantity'),
        ),
    ]
