# Generated by Django 3.1.3 on 2020-11-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0031_auto_20201127_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Your order has been placed', max_length=100),
        ),
    ]
