# Generated by Django 3.1.3 on 2020-11-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0032_auto_20201128_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliverytime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
