# Generated by Django 3.1.3 on 2020-11-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0033_auto_20201128_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending',
            old_name='items',
            new_name='item',
        ),
    ]
