# Generated by Django 3.1.3 on 2020-11-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0034_auto_20201128_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='Your order has been placed'),
        ),
    ]
