# Generated by Django 3.1.3 on 2020-11-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0035_auto_20201128_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food_items.itemperquantity')),
                ('restaurant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food_items.restaurant')),
            ],
        ),
    ]
