# Generated by Django 3.1.3 on 2020-11-28 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0037_auto_20201128_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning', models.FloatField(default=0.0)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food_items.restaurant')),
            ],
        ),
    ]
