# Generated by Django 3.1.3 on 2020-11-28 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201110_2105'),
        ('food_items', '0038_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='Your order has been placed.'),
        ),
    ]
