# Generated by Django 3.1.3 on 2020-11-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0039_auto_20201128_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='customer',
        ),
    ]
