# Generated by Django 3.1.3 on 2020-11-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201110_2105'),
        ('food_items', '0040_remove_history_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='home.customer'),
        ),
    ]
