# Generated by Django 3.1.3 on 2020-11-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0041_history_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='customer',
            field=models.CharField(default='root', max_length=100),
        ),
    ]
