# Generated by Django 3.1.3 on 2020-11-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0042_auto_20201128_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='root', max_length=100)),
                ('item', models.CharField(default='', max_length=150)),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food_items.restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
