# Generated by Django 3.1.3 on 2020-11-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0043_auto_20201128_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyoforders',
            name='customer',
        ),
    ]
