# Generated by Django 3.1.3 on 2020-11-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201110_2105'),
        ('food_items', '0044_remove_historyoforders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyoforders',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
