# Generated by Django 3.1.3 on 2020-11-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0046_auto_20201128_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryOfOrders',
        ),
    ]
