# Generated by Django 3.1.3 on 2020-11-28 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0055_delete_customerorderhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food_items.restaurant'),
        ),
    ]
