# Generated by Django 3.1.3 on 2020-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0056_auto_20201128_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
