# Generated by Django 3.1.3 on 2020-11-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0057_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food_items.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='Your order has been placed.'),
        ),
    ]
